num = int(input('Digite um número para ver sua tabuada: '))
cont = int(1)
print('-----------------')
print('{} x {} = {}'.format(num, cont, (num*cont)))
print('{} x {} = {}'.format(num, cont+1, (num*(cont+1))))
print('{} x {} = {}'.format(num, cont+2, (num*(cont+2))))
print('{} x {} = {}'.format(num, cont+3, (num*(cont+3))))
print('{} x {} = {}'.format(num, cont+4, (num*(cont+4))))
print('{} x {} = {}'.format(num, cont+5, (num*(cont+5))))
print('{} x {} = {}'.format(num, cont+6, (num*(cont+6))))
print('{} x {} = {}'.format(num, cont+7, (num*(cont+7))))
print('{} x {} = {}'.format(num, cont+8, (num*(cont+8))))
print('{} x {} = {}'.format(num, cont+9, (num*(cont+9))))
print('-----------------')