nome = input('Digite seu nome completo: ').strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}.'.format(nome.upper()))
print('Seu nome em minúsculas é {}.'.format(nome.lower()))
print('Seu ao todo tem {} letras.'.format(len(nome) - nome.count(' ')))
listanome = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.'.format(listanome[0], len(listanome[0])))